
services:

    dev-db: 
      image: registry.sedrehgroup.ir/postgres:16-alpine
      restart: always
      ports:
        - "5432:5432"
      env_file:
      - .env
      volumes:
        - ./scripts:/docker-entrypoint-initdb.d
      networks:
        - main

    pgadmin:
      container_name : pgadmin
      image: registry.sedrehgroup.ir/pgadmin4
      ports : 
      -  '5050:80'
      env_file:
      - .env
      networks:
      - main

networks:
  main:
