"""empty message

Revision ID: e9bce702bf69
Revises: 
Create Date: 2025-01-11 14:07:22.689951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9bce702bf69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('level', sa.Integer(), server_default='100', nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('LENGTH(name) > 0', name='name_length_check'),
    sa.CheckConstraint('LENGTH(slug) > 0', name='slug_length_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'level', name='unique_category_name_level'),
    sa.UniqueConstraint('slug', name='unique_category_slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
